name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
template: |
  ## What's Changed

  $CHANGES
  
  [Docs](https://public-value-tech.github.io/v$NEXT_PATCH_VERSION/documentation/playbutton/index.html)
change-template: "TITLE (#$NUMBER thanks @$AUTHOR)"
