name: build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    name: "Run Tests"
    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode Version
      run: sudo xcode-select --switch /Applications/Xcode_14.1.app
    - name: Run tests
      run: xcodebuild test -scheme PlayButton -destination "OS=16.1,name=iPhone 11"
